---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - path: patch-deployment.yml
    target:
      kind: Deployment
      name: dev-app
    options:
      allowNameChange: true
#labels:
#  env: dev
labels:
  - pairs:
      env: dev-test
      you: me
