kind: Deployment
metadata:
  name: dev-app
spec:
  replicas: 2
  template:
    metadata:
      name: jay-pod
      labels:
        env: dev
    spec:
      containers:
        - name: web
          ports:
            - containerPort: 8080
            - containerPort: 8443
          resources:
            requests:
              cpu: "10m"
              memory: "20Mi"
