apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: secret-ibm
data:
  password: bXlwYTU1
  root_password: cjAwdHBhNTU=

# oc create secret generic cm-secret --from-literal password=mypa55 --from-literal root_password=r00tpa55 --dry-run=client -o yaml
# echo bXlwYTU1 | base64 --decode


---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: cm-ibm
data:
  database: ibm
  user: paul

# oc create configmap cm-ibm --from-literal user=paul --from-literal database=ibm --dry-run=client -o yaml


---
apiVersion: v1
kind: Pod
metadata:
  name: jad-complex
spec:
  containers:
    - name: web
      image: registry.access.redhat.com/ubi9/httpd-24:9.7
      ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443

    - name: db
      image: registry.fedoraproject.org/f32/mysql
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: cm-ibm
              key: user
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: cm-ibm
              key: database

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-ibm
              key: password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-ibm
              key: root_password
