apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: null
  name: compute-quota
spec:
  hard:
    cpu: 100m
    limits.cpu: 200m
    limits.memory: 300Mi
    requests.memory: 200Mi
status: {}
# oc create quota compute-quota --hard cpu=100m,requests.memory=200Mi,limits.cpu=200m,limits.memory=300Mi --dry-run=client -o yaml > compute-quota.yml
