apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: onetime
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - date
        - +%D
        image: registry.access.redhat.com/ubi9/httpd-24:9.7
        name: onetime
        resources: {}
      restartPolicy: Never
status: {}
# oc create job onetime --dry-run=client -o yaml --image registry.access.redhat.com/ubi9/httpd-24:9.7 -- date +%D  > onetime.yml
