apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-app
  labels:
    app: dev
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      name: jay-pod
      labels:
        app: dev
    spec:
      containers:
        - name: web
          image: {{ .Values.web_image.repository }}:{{ .Values.web_image.tag }}
          ports:
            - containerPort: {{ .Values.web_image.port }}
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}

        - name: db
          image: {{ .Values.db_image.repository }}:{{ .Values.db_image.tag }}
          ports:
            - containerPort: {{ .Values.db_image.port }}
          env:
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: cm-ibm
                  key: user
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: cm-ibm
                  key: database
 
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-ibm
                  key: password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-ibm
                  key: root_password

